# -*- coding: utf-8 -*-
"""Assignment_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d42la6VqVreSKwrtJ7z6EtlUmxFCos3o
"""

import random as rd

#theory
mean_th = 50

#simulation
test_cases = 1000000
sum=0;

for i in range(test_cases):
  x = rd.uniform(0,100)
  sum += x

mean = sum/test_cases

print("Expected mean temperature according to theory = 50.0")
print("Mean temperature obtained by simulation is {}".format(mean))