# -*- coding: utf-8 -*-
"""Assignment 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dte68D0fW6IUfgEbwBIcCJcUoB4-DTt_
"""

import random as rd
import numpy as np
import matplotlib.pyplot as plt

#theory
#total no. of cards are 52
tot = 52
#no. of aces are 4
#therefore, favourable cases are 4 
fav = 4
#evidently, no. of unfavourable cases are 52-4 = 48
unfav = 48
#probability of picking an ace is p=4/52
p= 4/52
#probability of not picking an ace is q=48/52
q= 48/52
#since we are picking a card two times, there are 3 possible cases of picking aces, nameley,
# no aces(X=0)
# one ace(X=1)
# two aces(X=2)

#P(X=0) can be obtained by multiplying probability of not picking an ace, i.e. q^2
p0 = q*q
#P(X=1) can be obtained from multiplying probabilities of picking an ace and not picking an ace and considering the possibilities for order of occurances
p1 = p*q + q*p
#P(X=2) can be obtained by multiplying probability of picking an ace, i.e. p^2
p2 = p*p

#Simulation
test_cases = 1000000
deck = [x for x in range(52)]
for i in range(4):
  index = rd.randint(0,51)
  if deck[index]!='A': #let a card represented by A be an Ace
    deck[index] = 'A'
    i+=1

count_no_ace = 0
count_one_ace = 0
count_two_aces = 0

for i in range(test_cases+1):
  pick1 = rd.randint(0,51)
  pick2 = rd.randint(0,51)

  if deck[pick1]!='A' and deck[pick2]!='A':
    count_no_ace+=1
  elif deck[pick1]=='A' and deck[pick2]!='A':
    count_one_ace+=1
  elif deck[pick1]!='A' and deck[pick2]=='A':
    count_one_ace+=1
  elif deck[pick1]=='A' and deck[pick2]=='A':
    count_two_aces+=1

#P(X=0) will be:
prob_no_ace = count_no_ace/test_cases
#P(X=1) will be:
prob_one_ace = count_one_ace/test_cases
#P(X=2) will be:
prob_two_aces = count_two_aces/test_cases

print("The results according to theory are: ")
print("  P(X=0) = {}".format(p0))
print("  P(X=1) = {}".format(p1))
print("  P(X=2) = {}".format(p2))
print()
print("The results according to simulation are: ")
print("  P(X=0) = {}".format(prob_no_ace))
print("  P(X=1) = {}".format(prob_one_ace))
print("  P(X=2) = {}".format(prob_two_aces))
print()
print("The variations in probabilities calculated by theory and simulation are: ")
print("  error in P(X=0) = {}".format(abs(prob_no_ace-p0)))
print("  error in P(X=1) = {}".format(abs(prob_one_ace-p1)))
print("  error in P(X=2) = {}".format(abs(prob_two_aces-p2)))
print()
print("Since errors in probability found by the different methods are neglegible, we conclude that both results are same.")

#plotting
x_axis = ['X=0','X=1','X=2']
y_axis = [prob_no_ace,prob_one_ace,prob_two_aces]

plt.bar(x_axis, y_axis, width = 0.5, align= 'center', color=["#aa5500","#00ff00","#ff9e00"])
plt.title('Probability Distribution of no. of Aces Drawn')
plt.xlabel('Outcomes')
plt.ylabel('Probabilty')
plt.savefig("Bar_graph.png")
plt.show()

plt.pie(y_axis,labels = x_axis, colors=["#aa5500","#00ff00","#ff9e00"])
plt.title('Probability Distribution of no. of Aces Drawn')
plt.savefig("Pie_chart.png")
plt.show()