# -*- coding: utf-8 -*-
"""Assignment 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1guP9JNybSnMH-eED6PWnujM-U15v9d5l
"""

import random as rd

#theory
p=1/10 #probability of 2 being the first even number in the arrangement

#simulation
tests = 100000
count = 0
for iteration in range(tests):
  perm = [-1 for i in range(20)]
  j=1
  while j<=20:
    term = rd.randint(0,19)
    if perm[term] == -1:
      perm[term] = j
      j+=1

  for i in range(20):
    if perm[i]%2==0 and perm[i]!=2:
      break
    elif perm[i]==2:
      count+=1
      break

prob = count/tests
print("The theoretically calculated probability is {}".format(p))

print("The probability obtained from simuation is {}".format(prob))

print("Difference in the probabitities is {}".format(abs(prob-p)))

print("Since difference in probability found by the different methods are neglegible, we conclude that both results are same.")